name: base_bloc
description: A new Flutter plugin project.
version: 0.0.1
homepage: null
publish_to: none


environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  go_router: ^10.1.0
  provider: ^6.0.5
  shared:
    path: ../shared

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  injectable_generator: ^2.3.0
# flutter:
#   generate: true # Add this line
