name: base_bloc
description: A new Flutter plugin project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  dartx: ^1.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  go_router: ^10.1.0
  injectable: ^2.2.0
  intl: ^0.18.0
  package_info_plus: ^4.1.0
  rxdart: ^0.27.7
  shared:
    path: ../shared

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  injectable_generator: ^2.3.0

# flutter:
#   generate: true # Add this line
