name: botanic_gaze
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  app_ui:
    path: ./packages/app_ui
  appsflyer_sdk: ^6.12.2
  base_bloc:
    path: ./packages/base_bloc
  base_network:
    path: ./packages/base_network
  cached_network_image: ^3.2.3
  camera: 0.10.5
  device_info_plus: ^9.0.3
  dio: ^5.3.2
  equatable: ^2.0.5
  expandable: ^5.0.1
  firebase_core: ^2.16.0
  firebase_dynamic_links: ^5.3.7
  firebase_remote_config: ^4.2.7
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.2
  flutter_html_all: ^3.0.0-beta.2
  flutter_local_notifications: ^16.1.0
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  geolocator: ^10.0.1
  google_sign_in: ^6.1.5
  image_picker: ^1.0.2
  injectable: ^2.2.0
  intl: ^0.18.0
  paging_view:
    path: ./packages/paging_view
  permission_client:
    path: ./packages/permission_client
  photo_view: ^0.14.0
  scroll_to_index: ^3.0.1
  share_plus: null
  shared:
    path: ./packages/shared
  shared_preferences: ^2.2.0
  syncfusion_flutter_gauges: ^22.2.9

dev_dependencies:
  auto_route_generator: ^7.3.1
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.3.0
  melos: ^3.1.1
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/plant_type/
    - assets/icons/
