name: base_network
description: A new Flutter plugin project.
version: 0.0.1
homepage: null
publish_to: none

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  # colorize: ^3.0.0
  connectivity_plus: ^4.0.2
  dio: ^5.3.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  shared:
    path: ../shared
  tuple: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  injectable_generator: ^2.3.0
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
